### ISSUE TITLE
INPUT - Setting value of auro-input to undefined does not reset error state

### ISSUE THREAD

**Issue by ethanwmiller** [AlaskaAirlines/auro-formkit#118]
### Please verify the version of auro-input you have installed

2.15.1

### Please describe the bug

1. Create an error state on an auro-input component (for example, leaving a required field blank)
2. Programmatically set the input's value to `undefined`
3. The input's error state does not reset (pictured below)

<img width="577" alt="Screen Shot 2023-11-08 at 11 21 13 AM" src="https://github.com/AlaskaAirlines/auro-formkit/assets/126627409/b38f8a59-935c-4435-ab66-c8006ff20980">

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

When the value of auro-input is set to undefined, it should completely reset the component, including error states.

### What browsers are you seeing the problem on?

Chrome

**Comment by jordanjones243** [comment]
The work to give the user the ability to reset the component to it's intial state will be addressed in this ticket:
- https://github.com/AlaskaAirlines/auro-formkit/issues/135
