### ISSUE TITLE
SELECT: Truncate values

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-formkit#147]
# General Support Request

As a follow up to this issue AlaskaAirlines/auro-select#101 

With this demo, there was another issue discovered. If a select menu is shorter than the content of the menu, when a long string is selected, this presents an awkward experience. 

<img width="532" alt="Screen Shot 2022-09-09 at 2 09 55 PM" src="https://user-images.githubusercontent.com/181089/189446223-0a70b270-2c17-4dc8-95fd-4953fb71f8e4.png">

The element should support truncating the content within the trigger.

**Comment by jordanjones243** [comment]
This is no longer an issue, as the work to truncate long menu options is still in place.
