### ISSUE TITLE
DROPDOWN: Create `inline-block` trigger examples to match blueprint

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-formkit#57]
### General Support Request

In the component blueprint, there are examples of dropdowns with a trigger width as big as the size of its content. We need to add examples on the docsite to reflect those expectations.

### Possible Solution

Add examples with both a default trigger and a trigger using only an `auro-icon`.

### Additional context

Component blueprint:
- https://www.figma.com/design/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=1231-21886&node-type=rounded_rectangle&m=dev

How the examples should look:
![Screen Shot 2024-11-20 at 2 13 06 PM](https://github.com/user-attachments/assets/8d40f618-1778-4174-86fc-bcdfaed6d07f)

### Exit criteria

Examples are added to the docsite and reflect how they look within the blueprint.

**Comment by sun-mota** [comment]
add `fluid` attribute make the dropdown block and the default display will be inline-block
