### ISSUE TITLE
MENU/SELECT/COMBOBOX: UI needs to better handle slow loading of dynamic content

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-formkit#75]
## Describe the bug

The user is never notified via the UI that dynamic content is loading.

## To Reproduce

1. Go to https://www.alaskaair.com/search-test/
1. Open inspector and in the `network` tab, select a throttling option. Suggested `slow 3G`
1. Click in the "From" or "To" combobox
1. Type something
1. See error

## Expected behavior

Users can see that content is loading (ex. a loading icon)

**Comment by sun-mota** [comment]
change to `auro-menu`
add `loading` attribute 
- if true, hide all menu option and show only the predefined menu-option for the loading state with the loading slot
- this loading menu-option is disabled
add a slot for the loading text string
